### PR TITLE
adds support for lib_id for wf inputs

### PR DESCRIPTION
**Pull request by anilthanki**
Adding support for Galaxy to be able to run workflow using the Data Libraries, by utilising `library_id` of the dataset

### CODE REVIEW

**Comment by pcm32** [comment]
Can you please add a description above, so that if we come back to this in the future we know what it was about? Thanks.

**Review by pcm32 — COMMENTED** [review]
Great surgical intervention! 

I would like us though to add a bit of testing for this. I'll try to modify the workflow to receive a second file that we upload first to a library using parsec (which is already installed in the Github actions CI), then retrieve the library ID and change the inputs YAML to reflect this.

**Review by pcm32 — APPROVED** [review]
Ok, happy with this now that we have testing. Please take a look @anilthanki and let me know if you are fine with the changes I added.

**Comment by pcm32** [comment]
For the record, the issue with the user was that the admin user initially used to upload the file is some sort of a weird user in Galaxy terms, so the best was to create a new user from scratch and give it admin privs so that it could upload the file to the data library.

**Comment by anilthanki** [comment]
LGTM

**Pull request merged**
